### ISSUE TITLE
关于 node-gyp编译报错

### ISSUE THREAD

**Issue by badspider7** [bent2685/inksoo-lite#1]
你好我想问下你的python和vs的版本，我在pnpm i 的时候报错，应该是那个electron-acrylic-window 问题，但是我另一个项目里面也用了这个都ok的，所以想问下是不是版本的问题
![image](https://github.com/bent2685/inksoo-lite/assets/54093230/76d55b1c-1e36-4cc2-8a88-4c5a4aea6544)

**Comment by badspider7** [comment]
我把这个包卸载掉就可以了🎃

**Comment by bent2685** [comment]
> 你好我想问下你的python和vs的版本，我在pnpm i 的时候报错，应该是那个electron-acrylic-window 问题，但是我另一个项目里面也用了这个都ok的，所以想问下是不是版本的问题
> ![image](https://github.com/bent2685/inksoo-lite/assets/54093230/76d55b1c-1e36-4cc2-8a88-4c5a4aea6544)
> 

您好，这个是node-gyp依赖问题。我的开发机是mac, 在mac开发环境不会有这样的问题。在win下通常需要py2.7和vs2017+。另外vs需要添加vc++ tools依赖
